baseurl = "https://naomi-pet.club/"
languageCode = "es-es"
theme = "terminal"
paginate = 5
DefaultContentLanguage = "es"
enableRobotsTXT = true
[params]
  contentTypeName = "histories"
  themeColor = "pink"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  cover= "/img/naomi.jpg"
  web="https://kleber.digital"
  
[languages]
    [languages.es]
        title = "ğŸ¾ Naomi"
        subtitle = "La mascota de Kevin ğŸ’–"
        keywords = ""
        copyright = "kleber.digital"
        
        menuMore = "Mostrar mÃ¡s "
        readMore = "Leer mÃ¡s... ğŸ‘€"
        readOtherPosts = "mÃ¡s posts"
        
        [languages.es.params.logo]
        logoText = "Naomi"
        logoHomeLink = "/"

        [languages.es.menu]
        [[languages.es.menu.main]]
            identifier = "histories"
            name = "Historias"
            url = "/histories"
        [[languages.es.menu.main]]
            identifier = "gallery"
            name = "GalerÃ­a de fotos"   
            url = "/gallery"
        
    